### PR TITLE
Update 2018-05-18-building-projections-in-dotnet.md

### PR DESCRIPTION
**Pull request by eNeRGy164**
- Fix link
- Fix weird Unicode char
- Fix space

### CODE REVIEW

**Comment by dennisdoomen** [comment]
Thanks man!

**Comment by dennisdoomen** [comment]
Although I have to update https://liquidprojections.net/getting-started/ as well 😉

**Comment by eNeRGy164** [comment]
The edit button does not work there. Links to https://github.com/liquidprojections/liquidprojections/edit/master/docs/_pages/getting-started.md (404)

**Comment by eNeRGy164** [comment]
Guess that should link to https://github.com/liquidprojections/LiquidProjections.Docs/edit/master/_pages/getting-started.md

**Comment by dennisdoomen** [comment]
> Guess that should link to https://github.com/liquidprojections/LiquidProjections.Docs/edit/master/_pages/getting-started.md

Yep. Will fix that right away.

**Comment by eNeRGy164** [comment]
Probably https://github.com/liquidprojections/LiquidProjections.Docs/blob/master/_config.yml#L25

**Comment by dennisdoomen** [comment]
Fixed it.

**Pull request merged**
