### PR TITLE
Convert Most Recent posts to Markdown

### PR DESCRIPTION
**Pull request by SeanKilleen**
I figured since this blog can do markdown, we can convert the most recent few posts to take advantage of the clean editing capability. 

If you like this, we can try to apply similar efforts to other pages, depending on how far back you want to go.

I made the following sorts of changes:

* Converted headings `<h4>` to markdown equivalent `####`
* Replaced `<p>` and `<br>` with their markdown equivalent of 1-2 line breaks
* Converted lists to markdown format
* Downloaded the Fluent Assertions logo from its google location (see #25 for more on this) and referenced it via markdown
* Replaced the block quotes with `>` 
* Replaced the source code with markdown formatting which gives you the automatic highlighting
* Replaced all the links with markdown syntax
* Fixed a missing link
* Fixed a few typos along the way. :smile:

### CODE REVIEW

**Comment by SeanKilleen** [comment]
I also just found the nifty regex replace of `<a href="(.*)">(.*)</a>` with `[$2]($1)` very helpful while converting some links.

**Comment by SeanKilleen** [comment]
@dennisdoomen OK, this is ready for your 👀 . Converted the most recent 3 pages to markdown. You should be able to compare with the site side by side to see if there's anything off (I checked myself of course).

Converting these files makes them much easier to edit (they can be edited as markdown rather than as one continuous line of html).

**Comment by dennisdoomen** [comment]
Oh man, you already did the work. I don't know what to say....

**Comment by SeanKilleen** [comment]
Just some of them. Plenty more to go. 😄 Glad you're enjoying the PRs!

**Pull request merged**
