### PR TITLE
Update posts to use default layout

### PR DESCRIPTION
**Pull request by SeanKilleen**
Posts were set to use `layout: post` which stopped them from using the default layout. 

This fixes the posts, changing them to use the default layout.

### CODE REVIEW

**Comment by dennisdoomen** [comment]
Won't that break all the fancy stuff of the template that I'm using? E.g. Disquss integration, reading time, social sharing, etc?

**Comment by SeanKilleen** [comment]
@dennisdoomen sorry, I should have clarified. 

Currently, your individual posts don't appear to be using any of that fancy stuff. For example, prior to applying the post layout, your posts had no layout whatsoever -- when clicking a link, the below is what was rendered: 

> image

Because each of your individual posts uses a `post` layout (according to your front-matter), jekyll looks for a `post.html` in the `_layouts` folder. Prior to this PR, it simply didn't find anything (and 395 warnings were generated by Jekyll, one for each post).

In order to incorporate Disqus, social sharing, etc. you'll likely need to craft a `post` layout that makes use of these features. One may be available out of the box with the theme, but I don't see it included in this repo.

**Comment by SeanKilleen** [comment]
@dennisdoomen nevermind, I see what the issue is here:

Your `default` layout does all of this stuff. However, the blogger pages were generated with a `layout: post` in their front-matter, which doesn't exist. Hence the warnings, etc.

I thought a `post` layout needed to be created. But the default works perfectly, so we just need to remove `layout: post` from the rest of the posts. I'll do that as part of this PR.

**Comment by SeanKilleen** [comment]
Closing this to do it a little cleaner (and to avoid conflicts with the previous PR merge).

**Pull request closed without merging**
